championat.news.cron: 0 0/10 * * * *
rubilnik.scheduler.cron: 0 0 10 * * *

spring:
  datasource:
    url: jdbc:h2:file:~/bot/bot_db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
